module.exports = {
    success: 'success',
    error: 'error',
    unknownServerError: 'Unknown server error.',
    emailAlreadyRegistered: 'This email is already registered.',
    usernameAlreadyRegistered: 'This username is already registered.',
    // successfullyRegistered: 'Successfully registered. Please activate your account by validation email.',
    successfullyRegistered: 'Successfully registered. Please try to sign in.',
    emailIsInvalid: 'Your email is invalid',
    usernameIsInvalid: 'Your username is invalid',
    passwordIsInvalid: 'Your password is incorrect',
    successfullySignedIn: 'Successfully signed in',
    successfullySignedOut: 'Successfully signed out',
    error404: 'Not Fount',
    error500: 'Unknown server error',
    successfullySaved: 'Successfully saved',
    successfullyChanged: 'Successfully changed',
    successfullyDeleted: 'Successfully Deleted',
    currentPasswordIncorrect: 'Current password is incorrect',
    failedDueToUnknownServerError: 'Failed due to unknown server error',
    invalidParameters: 'Invalid Parameters',
};
